/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2010 Manfred Doudar, NICTA Ltd.
//
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
/////////////////////////////////////////////////////////////////////////////////////////////


#ifndef NICTA_VIBE_VIDEO_ALGORITHM_DETAIL_FOURCC_H
#define NICTA_VIBE_VIDEO_ALGORITHM_DETAIL_FOURCC_H

#include <static_association/static_association.h>

#include <opencv/highgui.h>


namespace nicta {
namespace vibe {
namespace video {
namespace algorithm {
namespace detail {

    // Known video codecs, for details see:  http://www.fourcc.org

    nicta::association<const char*, int> fourcc_assocArray[] = { { "3IV1" , CV_FOURCC('3', 'I', 'V', '1') },
                                                                 { "3IV2" , CV_FOURCC('3', 'I', 'V', '2') },
                                                                 { "8BPS" , CV_FOURCC('8', 'B', 'P', 'S') },
                                                                 { "AASC" , CV_FOURCC('A', 'A', 'S', 'C') },
                                                                 { "ABYR" , CV_FOURCC('A', 'B', 'Y', 'R') },
                                                                 { "ADV1" , CV_FOURCC('A', 'D', 'V', '1') },
                                                                 { "ADVJ" , CV_FOURCC('A', 'D', 'V', 'J') },
                                                                 { "AEMI" , CV_FOURCC('A', 'E', 'M', 'I') },
                                                                 { "AFLI" , CV_FOURCC('A', 'F', 'L', 'I') },
                                                                 { "AFLC" , CV_FOURCC('A', 'F', 'L', 'C') },
                                                                 { "AJPG" , CV_FOURCC('A', 'J', 'P', 'G') },
                                                                 { "AMPG" , CV_FOURCC('A', 'M', 'P', 'G') },
                                                                 { "ANIM" , CV_FOURCC('A', 'N', 'I', 'M') },
                                                                 { "AP41" , CV_FOURCC('A', 'P', '4', '1') },
                                                                 { "ASLC" , CV_FOURCC('A', 'S', 'L', 'C') },
                                                                 { "ASV1" , CV_FOURCC('A', 'S', 'V', '1') },
                                                                 { "ASV2" , CV_FOURCC('A', 'S', 'V', '2') },
                                                                 { "ASVX" , CV_FOURCC('A', 'S', 'V', 'X') },
                                                                 { "AUR2" , CV_FOURCC('A', 'U', 'R', '2') },
                                                                 { "AURA" , CV_FOURCC('A', 'U', 'R', 'A') },
                                                                 { "acv1" , CV_FOURCC('a', 'c', 'v', '1') },
                                                                 { "AVRn" , CV_FOURCC('A', 'V', 'R', 'n') },
                                                                 { "BA81" , CV_FOURCC('B', 'A', '8', '1') },
                                                                 { "BINK" , CV_FOURCC('B', 'I', 'N', 'K') },
                                                                 { "BLZ0" , CV_FOURCC('B', 'L', 'Z', '0') },
                                                                 { "BT20" , CV_FOURCC('B', 'T', '2', '0') },
                                                                 { "BTCV" , CV_FOURCC('B', 'T', 'C', 'V') },
                                                                 { "BW10" , CV_FOURCC('B', 'W', '1', '0') },
                                                                 { "BYR1" , CV_FOURCC('B', 'Y', 'R', '1') },
                                                                 { "BYR2" , CV_FOURCC('B', 'Y', 'R', '2') },
                                                                 { "CC12" , CV_FOURCC('C', 'C', '1', '2') },
                                                                 { "CDVC" , CV_FOURCC('C', 'D', 'V', 'C') },
                                                                 { "CFCC" , CV_FOURCC('C', 'F', 'C', 'C') },
                                                                 { "CGDI" , CV_FOURCC('C', 'G', 'D', 'I') },
                                                                 { "CHAM" , CV_FOURCC('C', 'H', 'A', 'M') },
                                                                 { "CMYK" , CV_FOURCC('C', 'M', 'Y', 'K') },
                                                                 { "CJPG" , CV_FOURCC('C', 'J', 'P', 'G') },
                                                                 { "CPLA" , CV_FOURCC('C', 'P', 'L', 'A') },
                                                                 { "CRAM" , CV_FOURCC('C', 'R', 'A', 'M') },
                                                                 { "CSCD" , CV_FOURCC('C', 'S', 'C', 'D') },
                                                                 { "CTRX" , CV_FOURCC('C', 'T', 'R', 'X') },
                                                                 { "CVID" , CV_FOURCC('C', 'V', 'I', 'D') },
                                                                 { "CWLT" , CV_FOURCC('C', 'W', 'L', 'T') },
                                                                 { "CXY1" , CV_FOURCC('C', 'X', 'Y', '1') },
                                                                 { "CXY2" , CV_FOURCC('C', 'X', 'Y', '2') },
                                                                 { "CYUV" , CV_FOURCC('C', 'Y', 'U', 'V') },
                                                                 { "CYUY" , CV_FOURCC('C', 'Y', 'U', 'Y') },
                                                                 { "D261" , CV_FOURCC('D', '2', '6', '1') },
                                                                 { "D263" , CV_FOURCC('D', '2', '6', '3') },
                                                                 { "davc" , CV_FOURCC('d', 'a', 'v', 'c') },
                                                                 { "DCL1" , CV_FOURCC('D', 'C', 'L', '1') },
                                                                 { "DCL2" , CV_FOURCC('D', 'C', 'L', '2') },
                                                                 { "DCL3" , CV_FOURCC('D', 'C', 'L', '3') },
                                                                 { "DCL4" , CV_FOURCC('D', 'C', 'L', '4') },
                                                                 { "DCL5" , CV_FOURCC('D', 'C', 'L', '5') },
                                                                 { "DIV3" , CV_FOURCC('D', 'I', 'V', '3') },
                                                                 { "DIV4" , CV_FOURCC('D', 'I', 'V', '4') },
                                                                 { "DIV5" , CV_FOURCC('D', 'I', 'V', '5') },
                                                                 { "DIVX" , CV_FOURCC('D', 'I', 'V', 'X') },
                                                                 { "divx" , CV_FOURCC('d', 'i', 'v', 'x') },
                                                                 { "DM4V" , CV_FOURCC('D', 'M', '4', 'V') },
                                                                 { "dmb1" , CV_FOURCC('d', 'm', 'b', '1') },
                                                                 { "DMB2" , CV_FOURCC('D', 'M', 'B', '2') },
                                                                 { "DMK2" , CV_FOURCC('D', 'M', 'K', '2') },
                                                                 { "DSVD" , CV_FOURCC('D', 'S', 'V', 'D') },
                                                                 { "DUCK" , CV_FOURCC('D', 'U', 'C', 'K') },
                                                                 { "dv25" , CV_FOURCC('d', 'v', '2', '5') },
                                                                 { "dv50" , CV_FOURCC('d', 'v', '5', '0') },
                                                                 { "DVAN" , CV_FOURCC('D', 'V', 'A', 'N') },
                                                                 { "DVCS" , CV_FOURCC('D', 'V', 'C', 'S') },
                                                                 { "DVE2" , CV_FOURCC('D', 'V', 'E', '2') },
                                                                 { "dvh1" , CV_FOURCC('d', 'v', 'h', '1') },
                                                                 { "dvhd" , CV_FOURCC('d', 'v', 'h', 'd') },
                                                                 { "DVSD" , CV_FOURCC('D', 'V', 'S', 'D') },
                                                                 { "dvsl" , CV_FOURCC('d', 'v', 's', 'l') },
                                                                 { "DVX1" , CV_FOURCC('D', 'V', 'X', '1') },
                                                                 { "DVX2" , CV_FOURCC('D', 'V', 'X', '2') },
                                                                 { "DVX3" , CV_FOURCC('D', 'V', 'X', '3') },
                                                                 { "DX50" , CV_FOURCC('D', 'X', '5', '0') },
                                                                 { "DXGM" , CV_FOURCC('D', 'X', 'G', 'M') },
                                                                 { "DXTn" , CV_FOURCC('D', 'X', 'T', 'n') },
                                                                 { "DXTC" , CV_FOURCC('D', 'X', 'T', 'C') },
                                                                 { "ELK0" , CV_FOURCC('E', 'L', 'K', '0') },
                                                                 { "EKQ0" , CV_FOURCC('E', 'K', 'Q', '0') },
                                                                 { "EM2V" , CV_FOURCC('E', 'M', '2', 'V') },
                                                                 { "ES07" , CV_FOURCC('E', 'S', '0', '7') },
                                                                 { "ESCP" , CV_FOURCC('E', 'S', 'C', 'P') },
                                                                 { "ETV1" , CV_FOURCC('E', 'T', 'V', '1') },
                                                                 { "ETV2" , CV_FOURCC('E', 'T', 'V', '2') },
                                                                 { "ETVC" , CV_FOURCC('E', 'T', 'V', 'C') },
                                                                 { "FFV1" , CV_FOURCC('F', 'F', 'V', '1') },
                                                                 { "FLJP" , CV_FOURCC('F', 'L', 'J', 'P') },
                                                                 { "FLV1" , CV_FOURCC('F', 'L', 'V', '1') },
                                                                 { "FMP4" , CV_FOURCC('F', 'M', 'P', '4') },
                                                                 { "FMVC" , CV_FOURCC('F', 'M', 'V', 'C') },
                                                                 { "FPS1" , CV_FOURCC('F', 'P', 'S', '1') },
                                                                 { "FRWA" , CV_FOURCC('F', 'R', 'W', 'A') },
                                                                 { "FRWD" , CV_FOURCC('F', 'R', 'W', 'D') },
                                                                 { "FVF1" , CV_FOURCC('F', 'V', 'F', '1') },
                                                                 { "GEOX" , CV_FOURCC('G', 'E', 'O', 'X') },
                                                                 { "GJPG" , CV_FOURCC('G', 'J', 'P', 'G') },
                                                                 { "GLZW" , CV_FOURCC('G', 'L', 'Z', 'W') },
                                                                 { "GPEG" , CV_FOURCC('G', 'P', 'E', 'G') },
                                                                 { "GWLT" , CV_FOURCC('G', 'W', 'L', 'T') },
                                                                 { "H260" , CV_FOURCC('H', '2', '6', '0') },
                                                                 { "H261" , CV_FOURCC('H', '2', '6', '1') },
                                                                 { "H262" , CV_FOURCC('H', '2', '6', '2') },
                                                                 { "H263" , CV_FOURCC('H', '2', '6', '3') },
                                                                 { "H264" , CV_FOURCC('H', '2', '6', '4') },
                                                                 { "H265" , CV_FOURCC('H', '2', '6', '5') },
                                                                 { "H266" , CV_FOURCC('H', '2', '6', '6') },
                                                                 { "H267" , CV_FOURCC('H', '2', '6', '7') },
                                                                 { "H268" , CV_FOURCC('H', '2', '6', '8') },
                                                                 { "H269" , CV_FOURCC('H', '2', '6', '9') },
                                                                 { "HDYC" , CV_FOURCC('H', 'D', 'Y', 'C') },
                                                                 { "HFYU" , CV_FOURCC('H', 'F', 'Y', 'U') },
                                                                 { "HMCR" , CV_FOURCC('H', 'M', 'C', 'R') },
                                                                 { "HMRR" , CV_FOURCC('H', 'M', 'R', 'R') },
                                                                 { "i263" , CV_FOURCC('i', '2', '6', '3') },
                                                                 { "I263" , CV_FOURCC('I', '2', '6', '3') },
                                                                 { "IAN"  , CV_FOURCC('I', 'A', 'N', ' ') },
                                                                 { "IAN " , CV_FOURCC('I', 'A', 'N', ' ') },
                                                                 { "ICLB" , CV_FOURCC('I', 'C', 'L', 'B') },
                                                                 { "IGOR" , CV_FOURCC('I', 'G', 'O', 'R') },
                                                                 { "IJPG" , CV_FOURCC('I', 'J', 'P', 'G') },
                                                                 { "ILVC" , CV_FOURCC('I', 'L', 'V', 'C') },
                                                                 { "ILVR" , CV_FOURCC('I', 'L', 'V', 'R') },
                                                                 { "IPDV" , CV_FOURCC('I', 'P', 'D', 'V') },
                                                                 { "IR21" , CV_FOURCC('I', 'R', '2', '1') },
                                                                 { "IRAW" , CV_FOURCC('I', 'R', 'A', 'W') },
                                                                 { "ISME" , CV_FOURCC('I', 'S', 'M', 'E') },
                                                                 { "IV30" , CV_FOURCC('I', 'V', '3', '0') },
                                                                 { "IV31" , CV_FOURCC('I', 'V', '3', '1') },
                                                                 { "IV32" , CV_FOURCC('I', 'V', '3', '2') },
                                                                 { "IV33" , CV_FOURCC('I', 'V', '3', '3') },
                                                                 { "IV34" , CV_FOURCC('I', 'V', '3', '4') },
                                                                 { "IV35" , CV_FOURCC('I', 'V', '3', '5') },
                                                                 { "IV36" , CV_FOURCC('I', 'V', '3', '6') },
                                                                 { "IV37" , CV_FOURCC('I', 'V', '3', '7') },
                                                                 { "IV38" , CV_FOURCC('I', 'V', '3', '8') },
                                                                 { "IV39" , CV_FOURCC('I', 'V', '3', '9') },
                                                                 { "IV40" , CV_FOURCC('I', 'V', '4', '0') },
                                                                 { "IV41" , CV_FOURCC('I', 'V', '4', '1') },
                                                                 { "IV42" , CV_FOURCC('I', 'V', '4', '2') },
                                                                 { "IV43" , CV_FOURCC('I', 'V', '4', '3') },
                                                                 { "IV44" , CV_FOURCC('I', 'V', '4', '4') },
                                                                 { "IV45" , CV_FOURCC('I', 'V', '4', '5') },
                                                                 { "IV46" , CV_FOURCC('I', 'V', '4', '6') },
                                                                 { "IV47" , CV_FOURCC('I', 'V', '4', '7') },
                                                                 { "IV48" , CV_FOURCC('I', 'V', '4', '8') },
                                                                 { "IV49" , CV_FOURCC('I', 'V', '4', '9') },
                                                                 { "IV50" , CV_FOURCC('I', 'V', '5', '0') },
                                                                 { "JBYR" , CV_FOURCC('J', 'B', 'Y', 'R') },
                                                                 { "jpeg" , CV_FOURCC('j', 'p', 'e', 'g') },
                                                                 { "JPEG" , CV_FOURCC('J', 'P', 'E', 'G') },
                                                                 { "JPGL" , CV_FOURCC('J', 'P', 'G', 'L') },
                                                                 { "KMVC" , CV_FOURCC('K', 'M', 'V', 'C') },
                                                                 { "L261" , CV_FOURCC('L', '2', '6', '1') },
                                                                 { "L263" , CV_FOURCC('L', '2', '6', '3') },
                                                                 { "LBYR" , CV_FOURCC('L', 'B', 'Y', 'R') },
                                                                 { "LCMW" , CV_FOURCC('L', 'C', 'M', 'W') },
                                                                 { "LCW2" , CV_FOURCC('L', 'C', 'W', '2') },
                                                                 { "LEAD" , CV_FOURCC('L', 'A', 'E', 'D') },
                                                                 { "LGRY" , CV_FOURCC('L', 'G', 'R', 'Y') },
                                                                 { "LJ11" , CV_FOURCC('L', 'J', '1', '1') },
                                                                 { "LJ22" , CV_FOURCC('L', 'J', '2', '2') },
                                                                 { "LJ2K" , CV_FOURCC('L', 'J', '2', 'K') },
                                                                 { "LJ44" , CV_FOURCC('L', 'J', '4', '4') },
                                                                 { "Ljpg" , CV_FOURCC('L', 'j', 'p', 'g') },
                                                                 { "LMP2" , CV_FOURCC('L', 'M', 'P', '2') },
                                                                 { "LMP4" , CV_FOURCC('L', 'M', 'P', '4') },
                                                                 { "LSVC" , CV_FOURCC('L', 'S', 'V', 'C') },
                                                                 { "LSVM" , CV_FOURCC('L', 'S', 'V', 'M') },
                                                                 { "LSVX" , CV_FOURCC('L', 'S', 'V', 'X') },
                                                                 { "LZO1" , CV_FOURCC('L', 'Z', 'O', '1') },
                                                                 { "M263" , CV_FOURCC('M', '2', '6', '3') },
                                                                 { "M261" , CV_FOURCC('M', '2', '6', '1') },
                                                                 { "m4cc" , CV_FOURCC('m', '4', 'c', 'c') },
                                                                 { "M4CC" , CV_FOURCC('M', '4', 'C', 'C') },
                                                                 { "M4S2" , CV_FOURCC('M', '4', 'S', '2') },
                                                                 { "MC12" , CV_FOURCC('M', 'C', '1', '2') },
                                                                 { "MCAM" , CV_FOURCC('M', 'C', 'A', 'M') },
                                                                 { "MJ2C" , CV_FOURCC('M', 'J', '2', 'C') },
                                                                 { "mJPG" , CV_FOURCC('m', 'J', 'P', 'G') },
                                                                 { "MJPG" , CV_FOURCC('M', 'J', 'P', 'G') },
                                                                 { "MMES" , CV_FOURCC('M', 'M', 'E', 'S') },
                                                                 { "MP2A" , CV_FOURCC('M', 'P', '2', 'A') },
                                                                 { "MP2T" , CV_FOURCC('M', 'P', '2', 'T') },
                                                                 { "MP2V" , CV_FOURCC('M', 'P', '2', 'V') },
                                                                 { "MP42" , CV_FOURCC('M', 'P', '4', '2') },
                                                                 { "MP43" , CV_FOURCC('M', 'P', '4', '3') },
                                                                 { "MP4A" , CV_FOURCC('M', 'P', '4', 'A') },
                                                                 { "MP4S" , CV_FOURCC('M', 'P', '4', 'S') },
                                                                 { "MP4T" , CV_FOURCC('M', 'P', '4', 'T') },
                                                                 { "mp4v" , CV_FOURCC('m', 'p', '4', 'v') },
                                                                 { "MP4V" , CV_FOURCC('M', 'P', '4', 'V') },
                                                                 { "MPEG" , CV_FOURCC('M', 'P', 'E', 'G') },
                                                                 { "MPG4" , CV_FOURCC('M', 'P', 'G', '4') },
                                                                 { "MPGI" , CV_FOURCC('M', 'P', 'G', 'I') },
                                                                 { "MR16" , CV_FOURCC('M', 'R', '1', '6') },
                                                                 { "MRCA" , CV_FOURCC('M', 'R', 'C', 'A') },
                                                                 { "MRLE" , CV_FOURCC('M', 'R', 'L', 'E') },
                                                                 { "MSVC" , CV_FOURCC('M', 'S', 'V', 'C') },
                                                                 { "MSZH" , CV_FOURCC('M', 'S', 'Z', 'H') },
                                                                 { "MTX1" , CV_FOURCC('M', 'T', 'X', '1') },
                                                                 { "MTX2" , CV_FOURCC('M', 'T', 'X', '2') },
                                                                 { "MTX3" , CV_FOURCC('M', 'T', 'X', '3') },
                                                                 { "MTX4" , CV_FOURCC('M', 'T', 'X', '4') },
                                                                 { "MTX5" , CV_FOURCC('M', 'T', 'X', '5') },
                                                                 { "MTX6" , CV_FOURCC('M', 'T', 'X', '6') },
                                                                 { "MTX7" , CV_FOURCC('M', 'T', 'X', '7') },
                                                                 { "MTX8" , CV_FOURCC('M', 'T', 'X', '8') },
                                                                 { "MTX9" , CV_FOURCC('M', 'T', 'X', '9') },
                                                                 { "MVI1" , CV_FOURCC('M', 'V', 'I', '1') },
                                                                 { "MVI2" , CV_FOURCC('M', 'V', 'I', '2') },
                                                                 { "MWV1" , CV_FOURCC('M', 'W', 'V', '1') },
                                                                 { "nAVI" , CV_FOURCC('n', 'A', 'V', 'I') },
                                                                 { "NDSC" , CV_FOURCC('N', 'D', 'S', 'C') },
                                                                 { "ndsm" , CV_FOURCC('n', 'd', 's', 'm') },
                                                                 { "ndsp" , CV_FOURCC('n', 'd', 's', 'p') },
                                                                 { "NDSP" , CV_FOURCC('N', 'D', 'S', 'P') },
                                                                 { "ndss" , CV_FOURCC('n', 'd', 's', 's') },
                                                                 { "NDSS" , CV_FOURCC('N', 'D', 'S', 'S') },
                                                                 { "NDXC" , CV_FOURCC('N', 'D', 'X', 'C') },
                                                                 { "NDXH" , CV_FOURCC('N', 'D', 'X', 'H') },
                                                                 { "NDXP" , CV_FOURCC('N', 'D', 'X', 'P') },
                                                                 { "NDXS" , CV_FOURCC('N', 'D', 'X', 'S') },
                                                                 { "NTN1" , CV_FOURCC('N', 'T', 'N', '1') },
                                                                 { "NTN2" , CV_FOURCC('N', 'T', 'N', '2') },
                                                                 { "NVDS" , CV_FOURCC('N', 'V', 'D', 'S') },
                                                                 { "NVHS" , CV_FOURCC('N', 'V', 'H', 'S') },
                                                                 { "NHVU" , CV_FOURCC('N', 'H', 'V', 'U') },
                                                                 { "NVS0" , CV_FOURCC('N', 'V', 'S', '0') },
                                                                 { "NVS1" , CV_FOURCC('N', 'V', 'S', '1') },
                                                                 { "NVS2" , CV_FOURCC('N', 'V', 'S', '2') },
                                                                 { "NVS3" , CV_FOURCC('N', 'V', 'S', '3') },
                                                                 { "NVS4" , CV_FOURCC('N', 'V', 'S', '4') },
                                                                 { "NVS5" , CV_FOURCC('N', 'V', 'S', '5') },
                                                                 { "NVT0" , CV_FOURCC('N', 'V', 'T', '0') },
                                                                 { "NVT1" , CV_FOURCC('N', 'V', 'T', '1') },
                                                                 { "NVT2" , CV_FOURCC('N', 'V', 'T', '2') },
                                                                 { "NVT3" , CV_FOURCC('N', 'V', 'T', '3') },
                                                                 { "NVT4" , CV_FOURCC('N', 'V', 'T', '4') },
                                                                 { "NVT5" , CV_FOURCC('N', 'V', 'T', '5') },
                                                                 { "PDVC" , CV_FOURCC('P', 'D', 'V', 'C') },
                                                                 { "PGVV" , CV_FOURCC('P', 'G', 'V', 'V') },
                                                                 { "PHMO" , CV_FOURCC('P', 'H', 'M', 'O') },
                                                                 { "PIM1" , CV_FOURCC('P', 'I', 'M', '1') },
                                                                 { "PIM2" , CV_FOURCC('P', 'I', 'M', '2') },
                                                                 { "pimj" , CV_FOURCC('p', 'i', 'm', 'j') },
                                                                 { "PIXL" , CV_FOURCC('P', 'I', 'X', 'L') },
                                                                 { "PJPG" , CV_FOURCC('P', 'J', 'P', 'G') },
                                                                 { "PVEZ" , CV_FOURCC('P', 'V', 'E', 'Z') },
                                                                 { "PVMM" , CV_FOURCC('P', 'V', 'M', 'M') },
                                                                 { "PVW2" , CV_FOURCC('P', 'V', 'W', '2') },
                                                                 { "qpeg" , CV_FOURCC('q', 'p', 'e', 'g') },
                                                                 { "QPEG" , CV_FOURCC('Q', 'P', 'E', 'G') },
                                                                 { "raw"  , CV_FOURCC('r', 'a', 'w', ' ') },
                                                                 { "raw " , CV_FOURCC('r', 'a', 'w', ' ') },
                                                                 { "RGBT" , CV_FOURCC('R', 'G', 'B', 'T') },
                                                                 { "rle"  , CV_FOURCC('r', 'l', 'e', ' ') },
                                                                 { "rle " , CV_FOURCC('r', 'l', 'e', ' ') },
                                                                 { "RLE"  , CV_FOURCC('R', 'L', 'E', ' ') },
                                                                 { "RLE " , CV_FOURCC('R', 'L', 'E', ' ') },
                                                                 { "RLE4" , CV_FOURCC('R', 'L', 'E', '4') },
                                                                 { "RLE8" , CV_FOURCC('R', 'L', 'E', '8') },
                                                                 { "RMP4" , CV_FOURCC('R', 'M', 'P', '4') },
                                                                 { "RPZA" , CV_FOURCC('R', 'P', 'Z', 'A') },
                                                                 { "RT21" , CV_FOURCC('R', 'T', '2', '1') },
                                                                 { "rv20" , CV_FOURCC('r', 'v', '2', '0') },
                                                                 { "rv30" , CV_FOURCC('r', 'v', '3', '0') },
                                                                 { "RVX"  , CV_FOURCC('R', 'V', 'X', ' ') },
                                                                 { "RVX " , CV_FOURCC('R', 'V', 'X', ' ') },
                                                                 { "s422" , CV_FOURCC('s', '4', '2', '2') },
                                                                 { "SAN3" , CV_FOURCC('S', 'A', 'N', '3') },
                                                                 { "SDCC" , CV_FOURCC('S', 'D', 'C', 'C') },
                                                                 { "SEDG" , CV_FOURCC('S', 'E', 'D', 'G') },
                                                                 { "SFMC" , CV_FOURCC('S', 'F', 'M', 'C') },
                                                                 { "SMC"  , CV_FOURCC('S', 'M', 'C', ' ') },
                                                                 { "SMC " , CV_FOURCC('S', 'M', 'C', ' ') },
                                                                 { "SMP4" , CV_FOURCC('S', 'M', 'P', '4') },
                                                                 { "SMSC" , CV_FOURCC('S', 'M', 'S', 'C') },
                                                                 { "SMSD" , CV_FOURCC('S', 'M', 'S', 'D') },
                                                                 { "smsv" , CV_FOURCC('s', 'm', 's', 'v') },
                                                                 { "SP40" , CV_FOURCC('S', 'P', '4', '0') },
                                                                 { "SP44" , CV_FOURCC('S', 'P', '4', '4') },
                                                                 { "SP54" , CV_FOURCC('S', 'P', '5', '4') },
                                                                 { "SPIG" , CV_FOURCC('S', 'P', 'I', 'G') },
                                                                 { "SQZ2" , CV_FOURCC('S', 'Z', 'Z', '2') },
                                                                 { "SV10" , CV_FOURCC('S', 'V', '1', '0') },
                                                                 { "STVA" , CV_FOURCC('S', 'T', 'V', 'A') },
                                                                 { "STVB" , CV_FOURCC('S', 'T', 'V', 'B') },
                                                                 { "STVC" , CV_FOURCC('S', 'T', 'V', 'C') },
                                                                 { "STVX" , CV_FOURCC('S', 'T', 'V', 'X') },
                                                                 { "STVY" , CV_FOURCC('S', 'T', 'V', 'Y') },
                                                                 { "SVQ1" , CV_FOURCC('S', 'V', 'Q', '1') },
                                                                 { "SVQ3" , CV_FOURCC('S', 'V', 'Q', '3') },
                                                                 { "TLMS" , CV_FOURCC('T', 'L', 'M', 'S') },
                                                                 { "TLST" , CV_FOURCC('T', 'L', 'S', 'T') },
                                                                 { "TM20" , CV_FOURCC('T', 'M', '2', '0') },
                                                                 { "TM2X" , CV_FOURCC('T', 'M', '2', 'X') },
                                                                 { "TMIC" , CV_FOURCC('T', 'M', 'I', 'C') },
                                                                 { "TMOT" , CV_FOURCC('T', 'M', 'O', 'T') },
                                                                 { "TR20" , CV_FOURCC('T', 'R', '2', '0') },
                                                                 { "TSCC" , CV_FOURCC('T', 'S', 'C', 'C') },
                                                                 { "TV10" , CV_FOURCC('T', 'V', '1', '0') },
                                                                 { "TVJP" , CV_FOURCC('T', 'V', 'J', 'P') },
                                                                 { "TVMJ" , CV_FOURCC('T', 'V', 'M', 'J') },
                                                                 { "TY2C" , CV_FOURCC('T', 'Y', '2', 'C') },
                                                                 { "TY2N" , CV_FOURCC('T', 'Y', '2', 'N') },
                                                                 { "TY0N" , CV_FOURCC('T', 'Y', '0', 'N') },
                                                                 { "U263" , CV_FOURCC('U', '2', '6', '3') },
                                                                 { "UCOD" , CV_FOURCC('U', 'C', 'O', 'D') },
                                                                 { "ULTI" , CV_FOURCC('U', 'L', 'T', 'I') },
                                                                 { "v210" , CV_FOURCC('v', '2', '1', '0') },
                                                                 { "V261" , CV_FOURCC('V', '2', '6', '1') },
                                                                 { "V655" , CV_FOURCC('V', '6', '5', '5') },
                                                                 { "VCR1" , CV_FOURCC('V', 'C', 'R', '1') },
                                                                 { "VCR2" , CV_FOURCC('V', 'C', 'R', '2') },
                                                                 { "VCR3" , CV_FOURCC('V', 'C', 'R', '3') },
                                                                 { "VCR4" , CV_FOURCC('V', 'C', 'R', '4') },
                                                                 { "VCR5" , CV_FOURCC('V', 'C', 'R', '5') },
                                                                 { "VCR6" , CV_FOURCC('V', 'C', 'R', '6') },
                                                                 { "VCR7" , CV_FOURCC('V', 'C', 'R', '7') },
                                                                 { "VCR8" , CV_FOURCC('V', 'C', 'R', '8') },
                                                                 { "VCR9" , CV_FOURCC('V', 'C', 'R', '9') },
                                                                 { "VDCT" , CV_FOURCC('V', 'D', 'C', 'T') },
                                                                 { "VDOM" , CV_FOURCC('V', 'D', 'O', 'M') },
                                                                 { "VDOW" , CV_FOURCC('V', 'D', 'O', 'W') },
                                                                 { "VDTZ" , CV_FOURCC('V', 'D', 'T', 'Z') },
                                                                 { "VGPX" , CV_FOURCC('V', 'G', 'P', 'X') },
                                                                 { "VIFP" , CV_FOURCC('V', 'I', 'F', 'P') },
                                                                 { "VIDS" , CV_FOURCC('V', 'I', 'D', 'S') },
                                                                 { "VIVO" , CV_FOURCC('V', 'I', 'V', 'O') },
                                                                 { "VIXL" , CV_FOURCC('V', 'I', 'X', 'L') },
                                                                 { "VLV1" , CV_FOURCC('V', 'L', 'V', '1') },
                                                                 { "VP30" , CV_FOURCC('V', 'P', '3', '0') },
                                                                 { "VP31" , CV_FOURCC('V', 'P', '3', '1') },
                                                                 { "VP40" , CV_FOURCC('V', 'P', '4', '0') },
                                                                 { "VP50" , CV_FOURCC('V', 'P', '5', '0') },
                                                                 { "VP60" , CV_FOURCC('V', 'P', '6', '0') },
                                                                 { "VP61" , CV_FOURCC('V', 'P', '6', '1') },
                                                                 { "VP62" , CV_FOURCC('V', 'P', '6', '2') },
                                                                 { "VQC1" , CV_FOURCC('V', 'Q', 'C', '1') },
                                                                 { "VQC2" , CV_FOURCC('V', 'Q', 'C', '2') },
                                                                 { "VQJC" , CV_FOURCC('V', 'Q', 'J', 'C') },
                                                                 { "vssv" , CV_FOURCC('v', 's', 's', 'v') },
                                                                 { "VX2K" , CV_FOURCC('V', 'X', '2', 'K') },
                                                                 { "VXSP" , CV_FOURCC('V', 'X', 'S', 'P') },
                                                                 { "VYU9" , CV_FOURCC('V', 'Y', 'U', '9') },
                                                                 { "VYUY" , CV_FOURCC('V', 'Y', 'U', 'Y') },
                                                                 { "WBVC" , CV_FOURCC('W', 'B', 'V', 'C') },
                                                                 { "WHAM" , CV_FOURCC('W', 'H', 'A', 'M') },
                                                                 { "WINX" , CV_FOURCC('W', 'I', 'N', 'X') },
                                                                 { "WJPG" , CV_FOURCC('W', 'J', 'P', 'G') },
                                                                 { "WMV1" , CV_FOURCC('W', 'M', 'V', '1') },
                                                                 { "WMV2" , CV_FOURCC('W', 'M', 'V', '2') },
                                                                 { "WMV3" , CV_FOURCC('W', 'M', 'V', '3') },
                                                                 { "WMVA" , CV_FOURCC('W', 'M', 'V', 'A') },
                                                                 { "WNV1" , CV_FOURCC('W', 'N', 'V', '1') },
                                                                 { "WVC1" , CV_FOURCC('W', 'V', 'C', '1') },
                                                                 { "x263" , CV_FOURCC('x', '2', '6', '3') },
                                                                 { "X264" , CV_FOURCC('X', '2', '6', '4') },
                                                                 { "XVID" , CV_FOURCC('X', 'V', 'I', 'D') },
                                                                 { "XLV0" , CV_FOURCC('X', 'V', 'L', '0') },
                                                                 { "XMPG" , CV_FOURCC('X', 'M', 'P', 'G') },
                                                                 { "XWV0" , CV_FOURCC('X', 'W', 'V', '0') },
                                                                 { "XWV1" , CV_FOURCC('X', 'W', 'V', '1') },
                                                                 { "XWV2" , CV_FOURCC('X', 'W', 'V', '2') },
                                                                 { "XWV3" , CV_FOURCC('X', 'W', 'V', '3') },
                                                                 { "XWV4" , CV_FOURCC('X', 'W', 'V', '4') },
                                                                 { "XWV5" , CV_FOURCC('X', 'W', 'V', '5') },
                                                                 { "XWV6" , CV_FOURCC('X', 'W', 'V', '6') },
                                                                 { "XWV7" , CV_FOURCC('X', 'W', 'V', '7') },
                                                                 { "XWV8" , CV_FOURCC('X', 'W', 'V', '8') },
                                                                 { "XWV9" , CV_FOURCC('X', 'W', 'V', '9') },
                                                                 { "XXAN" , CV_FOURCC('X', 'X', 'A', 'N') },
                                                                 { "Y16"  , CV_FOURCC('Y', '1', '6', ' ') },
                                                                 { "Y16 " , CV_FOURCC('Y', '1', '6', ' ') },
                                                                 { "Y411" , CV_FOURCC('Y', '4', '1', '1') },
                                                                 { "Y41P" , CV_FOURCC('Y', '4', '1', 'P') },
                                                                 { "Y444" , CV_FOURCC('Y', '4', '4', '4') },
                                                                 { "Y8"   , CV_FOURCC('Y', '8', ' ', ' ') },
                                                                 { "Y8  " , CV_FOURCC('Y', '8', ' ', ' ') },
                                                                 { "YC12" , CV_FOURCC('Y', 'C', '1', '2') },
                                                                 { "YUV8" , CV_FOURCC('Y', 'U', 'V', '8') },
                                                                 { "YUV9" , CV_FOURCC('Y', 'U', 'V', '9') },
                                                                 { "YUVP" , CV_FOURCC('Y', 'U', 'V', 'P') },
                                                                 { "YUY2" , CV_FOURCC('Y', 'U', 'Y', '2') },
                                                                 { "YUYV" , CV_FOURCC('Y', 'U', 'Y', 'V') },
                                                                 { "YV12" , CV_FOURCC('Y', 'V', '1', '2') },
                                                                 { "YV16" , CV_FOURCC('Y', 'V', '1', '6') },
                                                                 { "YV92" , CV_FOURCC('Y', 'V', '9', '2') },
                                                                 { "ZLIB" , CV_FOURCC('Z', 'L', 'I', 'B') },
                                                                 { "ZMBV" , CV_FOURCC('Z', 'M', 'B', 'V') },
                                                                 { "ZPEG" , CV_FOURCC('Z', 'P', 'E', 'G') },
                                                                 { "ZyGo" , CV_FOURCC('Z', 'y', 'G', 'o') },
                                                                 { "ZYYY" , CV_FOURCC('Z', 'Y', 'Y', 'Y') } };


    nicta::static_association<const char*, int> fourcc_assocMap
         (nicta::vibe::video::algorithm::detail::fourcc_assocArray,
          sizeof(nicta::vibe::video::algorithm::detail::fourcc_assocArray) / sizeof(nicta::vibe::video::algorithm::detail::fourcc_assocArray[0]));

} } } } } // namespace nicta::vibe::video::algorithm::detail


#endif
